terminate called after throwing an instance of 'std::runtime_error'
  what():  Invalid file to read!

